# Generated by Django 5.0.7 on 2024-08-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='caption',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='avatar',
            field=models.CharField(choices=[('avatar1.png', 'Avatar 1'), ('avatar2.png', 'Avatar 2'), ('avatar3.png', 'Avatar 3'), ('avatar4.png', 'Avatar 4'), ('custom avatar', 'Custom Upload')], default='', max_length=255),
        ),
    ]
